navigation:
    mall-orders:
        label: 'winter.mall::lang.common.orders'
        url: winter/mall/orders
        icon: icon-shopping-cart
        order: 801
        permissions:
            - 'winter.mall.*'
        sideMenu:
            mall-orders:
                label: 'winter.mall::lang.common.orders'
                url: winter/mall/orders
                icon: icon-check-circle
                permissions:
                    - winter.mall.manage_orders
            mall-discounts:
                label: 'winter.mall::lang.common.discounts'
                url: winter/mall/discounts
                icon: icon-gift
                permissions:
                    - winter.mall.manage_discounts
            mall-payment-log:
                label: 'winter.mall::lang.common.payments'
                url: winter/mall/paymentlogs
                icon: icon-money
                permissions:
                    - winter.mall.manage_payment_log
    mall-catalogue:
        label: 'winter.mall::lang.common.catalogue'
        url: winter/mall/products
        icon: icon-book
        order: 800
        permissions:
            - winter.mall.manage_products
        sideMenu:
            mall-products:
                label: 'winter.mall::lang.common.products'
                url: winter/mall/products
                icon: icon-cart-plus
                permissions:
                    - winter.mall.manage_products
            mall-reviews:
                label: 'winter.mall::lang.common.reviews'
                url: winter/mall/reviews
                icon: icon-star-half-full
                permissions:
                    - winter.mall.manage_reviews
            mall-services:
                label: 'winter.mall::lang.common.services'
                url: winter/mall/services
                icon: icon-plus-circle
                permissions:
                    - winter.mall.manage_services
            mall-categories:
                label: 'winter.mall::lang.common.categories'
                url: winter/mall/categories
                icon: icon-sitemap
                permissions:
                    - winter.mall.manage_categories
            mall-brands:
                label: 'winter.mall::lang.common.brands'
                url: winter/mall/brands
                icon: icon-cube
                permissions:
                    - winter.mall.manage_brands
            mall-properties:
                label: 'winter.mall::lang.common.properties'
                url: winter/mall/propertygroups
                icon: icon-tags
                permissions:
                    - winter.mall.manage_properties
permissions:
    winter.mall.manage_products:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_products'
    winter.mall.manage_categories:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_categories'
    winter.mall.manage_orders:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_orders'
    winter.mall.manage_discounts:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_discounts'
    winter.mall.settings.manage_general:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.settings.manage_general'
    winter.mall.settings.manage_payment_gateways:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.settings.manage_payment_gateways'
    winter.mall.settings.manage_currency:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.settings.manage_currency'
    winter.mall.settings.manage_payment_methods:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.settings.manage_payment_methods'
    winter.mall.manage_properties:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_properties'
    winter.mall.manage_customer_groups:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_customer_groups'
    winter.mall.manage_notifications:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_notifications'
    winter.mall.manage_price_categories:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_price_categories'
    winter.mall.manage_order_states:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_order_states'
    winter.mall.manage_shipping_methods:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_shipping_methods'
    winter.mall.manage_customer_addresses:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_customer_addresses'
    winter.mall.manage_payment_log:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_payment_log'
    winter.mall.manage_feeds:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_feeds'
    winter.mall.manage_wishlists:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_wishlists'
    winter.mall.manage_services:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_services'
    winter.mall.manage_reviews:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_reviews'
    winter.mall.manage_brands:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_brands'
