permissions:
    winter.mall.manage_products:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_products'
    winter.mall.manage_categories:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_categories'
    winter.mall.manage_orders:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_orders'
    winter.mall.manage_discounts:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_discounts'
    winter.mall.settings.manage_general:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.settings.manage_general'
    winter.mall.settings.manage_payment_gateways:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.settings.manage_payment_gateways'
    winter.mall.settings.manage_currency:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.settings.manage_currency'
    winter.mall.settings.manage_payment_methods:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.settings.manage_payment_methods'
    winter.mall.manage_properties:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_properties'
    winter.mall.manage_customer_groups:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_customer_groups'
    winter.mall.manage_notifications:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_notifications'
    winter.mall.manage_price_categories:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_price_categories'
    winter.mall.manage_order_states:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_order_states'
    winter.mall.manage_shipping_methods:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_shipping_methods'
    winter.mall.manage_customer_addresses:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_customer_addresses'
    winter.mall.manage_payment_log:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_payment_log'
    winter.mall.manage_feeds:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_feeds'
    winter.mall.manage_wishlists:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_wishlists'
    winter.mall.manage_services:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_services'
    winter.mall.manage_reviews:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_reviews'
    winter.mall.manage_brands:
        tab: 'winter.mall::lang.plugin.name'
        label: 'winter.mall::lang.permissions.manage_brands'
